# ======================================================================
# ArgoCD Application: framely-stage
#
# Environment:
# - Stage (Local KIND now, AKS Stage later)
#
# Purpose:
# - Connect ArgoCD with Git-based Kubernetes manifests
# - Continuously reconcile desired state from Git to the cluster
#
# GitOps Model:
# - Git is the single source of truth
# - Jenkins updates Git (image tags only)
# - ArgoCD applies changes to the cluster
#
# IMPORTANT:
# - Fully automated sync is INTENTIONAL for stage
# - Same file works for KIND and AKS
# ======================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: framely-stage
  namespace: argocd   # ArgoCD control-plane namespace (DO NOT CHANGE)
spec:
  # --------------------------------------------------------------------
  # ArgoCD Project (Security Boundary)
  # --------------------------------------------------------------------
  project: framely

  # --------------------------------------------------------------------
  # Source: Git repository containing Kubernetes manifests
  # --------------------------------------------------------------------
  source:
    repoURL: git@github.com:MrSharma151/framely-aks-mega-devops.git
    targetRevision: stage            # Track ONLY the 'stage' branch
    path: kubernetes/stage           # Stage-level GitOps manifests

    # Kustomize is used for environment-specific customization
    # Image tags are updated by Jenkins via GitOps commits
    kustomize: {}

    # FUTURE (OPTIONAL):
    # If switching to HTTPS repo access:
    # repoURL: https://github.com/MrSharma151/framely-aks-mega-devops.git

  # --------------------------------------------------------------------
  # Destination: Kubernetes cluster and namespace
  # --------------------------------------------------------------------
  destination:
    server: https://kubernetes.default.svc
    namespace: framely-stage

    # FUTURE (OPTIONAL – Multi-cluster AKS):
    # server: https://<AKS-STAGE-API-SERVER>

  # --------------------------------------------------------------------
  # Sync Policy: AUTOMATED (Stage = Continuous Deployment)
  # --------------------------------------------------------------------
  syncPolicy:
    automated:
      prune: true        # Remove resources deleted from Git
      selfHeal: true     # Revert any manual cluster drift

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

      # FUTURE (OPTIONAL):
      # - RespectIgnoreDifferences=true

  # --------------------------------------------------------------------
  # Application revision history retention
  # --------------------------------------------------------------------
  revisionHistoryLimit: 5
