# ======================================================================
# ArgoCD Application: framely-stage
#
# Environment:
# - Stage (Local KIND / Pre-Production)
#
# Purpose:
# - Connect ArgoCD with Kubernetes manifests stored in Git
# - Continuously reconcile the desired state from Git to the cluster
#
# This application:
# - Watches the kubernetes/stage directory
# - Deploys all Framely services into the framely-stage namespace
# - Follows strict GitOps principles (Git is the single source of truth)
# ======================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: framely-stage
  namespace: argocd                 # ArgoCD control-plane namespace
spec:
  # --------------------------------------------------------------------
  # ArgoCD Project this application belongs to
  # --------------------------------------------------------------------
  project: framely

  # --------------------------------------------------------------------
  # Source: Git repository containing Kubernetes manifests
  # --------------------------------------------------------------------
  source:
    repoURL: https://github.com/MrSharma151/framely-aks-mega-devops.git
    targetRevision: stage            # Track the 'stage' branch only
    path: kubernetes/stage           # GitOps manifests location

    # Kustomize is used for environment-specific customization
    # Image tags are automatically updated by Jenkins
    kustomize: {}

  # --------------------------------------------------------------------
  # Destination: Kubernetes cluster and target namespace
  # --------------------------------------------------------------------
  destination:
    server: https://kubernetes.default.svc
    namespace: framely-stage         # All resources are deployed here

  # --------------------------------------------------------------------
  # Sync Policy: Fully automated for Stage environment
  # --------------------------------------------------------------------
  syncPolicy:
    automated:
      prune: true                    # Delete resources removed from Git
      selfHeal: true                 # Revert any manual cluster changes

    syncOptions:
      - CreateNamespace=true         # Create namespace if it does not exist
      - ApplyOutOfSyncOnly=true      # Apply changes only when drift is detected

  # --------------------------------------------------------------------
  # Application revision history retention
  # --------------------------------------------------------------------
  revisionHistoryLimit: 5
