using System.ComponentModel.DataAnnotations;

namespace Framely.Core.DTOs
{
    /// <summary>
    /// Data Transfer Object representing an individual item in an order.
    /// Used for both order creation and retrieval.
    /// </summary>
    public class OrderItemDto
    {
        /// <summary>
        /// Unique identifier for the order item.
        /// Auto-generated by the system. Used in GET responses.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// ID of the product being ordered.
        /// Required during order creation.
        /// </summary>
        [Required(ErrorMessage = "Product ID is required")]
        public int ProductId { get; set; }

        /// <summary>
        /// Name of the product.
        /// Automatically filled in GET responses for display purposes.
        /// </summary>
        public string? ProductName { get; set; }

        /// <summary>
        /// Quantity of the product ordered.
        /// Must be at least 1.
        /// </summary>
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1")]
        public int Quantity { get; set; }

        /// <summary>
        /// Price per unit of the product at the time of order.
        /// Auto-calculated during order creation to preserve historical pricing.
        /// </summary>
        [Range(0.01, double.MaxValue, ErrorMessage = "Unit price must be greater than 0")]
        public decimal UnitPrice { get; set; }

        /// <summary>
        /// ID of the parent order.
        /// Automatically filled by the backend during order creation.
        /// </summary>
        public int OrderId { get; set; }
    }
}