using System.ComponentModel.DataAnnotations;

namespace Framely.Core.DTOs
{
    /// <summary>
    /// Data Transfer Object for creating, updating, or retrieving a product.
    /// Includes metadata, pricing, and category association.
    /// </summary>
    public class ProductDto
    {
        /// <summary>
        /// Unique identifier for the product.
        /// Auto-generated by the system. Used in GET responses.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Name of the product.
        /// Required field with a maximum length of 100 characters.
        /// </summary>
        [Required(ErrorMessage = "Product name is required")]
        [StringLength(100, ErrorMessage = "Product name cannot exceed 100 characters")]
        public string? Name { get; set; }

        /// <summary>
        /// Brand associated with the product.
        /// Required field with a maximum length of 50 characters.
        /// </summary>
        [Required(ErrorMessage = "Brand is required")]
        [StringLength(50, ErrorMessage = "Brand name cannot exceed 50 characters")]
        public string? Brand { get; set; }

        /// <summary>
        /// Optional description of the product.
        /// Maximum length is 500 characters.
        /// </summary>
        [StringLength(500, ErrorMessage = "Description cannot exceed 500 characters")]
        public string? Description { get; set; }

        /// <summary>
        /// Price of the product.
        /// Must be greater than zero.
        /// </summary>
        [Range(0.01, double.MaxValue, ErrorMessage = "Price must be greater than 0")]
        public decimal Price { get; set; }

        /// <summary>
        /// URL to the product image.
        /// Must be a valid URL format.
        /// </summary>
        [Url(ErrorMessage = "Invalid Image URL format")]
        public string? ImageUrl { get; set; }

        /// <summary>
        /// ID of the category the product belongs to.
        /// Required during creation and update.
        /// </summary>
        [Required(ErrorMessage = "Category ID is required")]
        public int CategoryId { get; set; }

        /// <summary>
        /// Name of the category.
        /// Auto-filled in GET responses for display purposes.
        /// </summary>
        public string? CategoryName { get; set; }
    }
}